### ISSUE TITLE
Replace 'ip' module

### ISSUE THREAD

**Issue by uhppoted** [uhppoted/uhppoted-nodejs#14]
Remove external dependency on _ip_ module since _uhppoted-nodejs_ only uses the IPv4 encoding/decoding functionality.

- [x] decoder.js
- [x] encoder.js
- [x] driver.js
- [x] integration tests

**Comment by twystd** [comment]
Replaced _ip.js_ functions with local equivalents, removed _ip.js_ from dependencies and updated documentation
