### ISSUE TITLE
Make it more conform... (back-port ;-)

### ISSUE THREAD

**Issue by kBrausew** [uhppoted/uhppoted-nodejs#5]
There is a dependency on nodejs V15.14.0.
This is not an LTS and also not common in the smart home area.
Would it be possible to do a backport here on 14.18.3?

internationalisation.js at line: https://github.com/uhppoted/uhppoted-nodejs/blob/caf18a248aa761be05b2df0d79c8fafc71041739/src/internationalisation.js#L101
`const translated = blob.replaceAll(/{{(.*?)}}/g, lookup)`
All you have to do is change ".replaceAll()" to ".replace()".
 ... and also the dependency ;-)

If not possible: Is it allowed to FORK for change it by myself?

**Comment by twystd** [comment]
Hi,

Thanks for the heads up!

Just taken a quick look at this - according to (my) _nvm_ the current LTS is 16.13.2? I've updated the `package.json` in the master branch accordingly - it's due for release _sometime soon_ (just waiting on a few obscure indirect dependencies to patch their security issues).

re. 14.18.3/smart homes. Hmmm - ok, valid point and I need to think about how to handle this going forward. For the moment I've created a [v14.18.3](https://github.com/uhppoted/uhppoted-nodejs/tree/node_v14.18.3) branch that downgrades the NodeJS engine requirement to 14.18.3 - looks ok on my system. Would you  mind trying it out in case their are hidden dependency issues that I've missed?

**Comment by kBrausew** [comment]
Many thanks for the super fast processing.
The functions all passed the quick test.

Problem: I would like to use the lib in ioBroker, but here I only have the option to install via NPM... so I always get version 0.7.1 (with warning message) which does not work under NodeJS 14.18.3.

If I have a working package for ioBroker... are you interested to link it in your overview?

**Comment by twystd** [comment]
Hi,

Kinda figured that might be an issue :-). From the reading and experimenting I've done there doesn't seem to be a downside to reducing the NodeJS version to 14.18.3 so I've merged the _nodejs_v14.18.3_ branch into the main branch.

I'll give it a day or so for any immediately serious security vulnerabilities to surface before I publish it if that's ok?

re. ioBroker/overview. Absolutely! Would be more than happy to link to it - let me once it's ready and I'll update the overview accordingly.

**Comment by kBrausew** [comment]
Great; this decision -   for me ;-)
Theoretically you could even go to 12.x.x without any disadvantages (... dependency to IP package )... (but I wouldn't recommend it)

When I'm in beta with the adapter, I'll report.

BTW: Is there a "subscribe"-package to the change log (npmjs.com) 
... or write here if you have changed it

**Comment by uhppoted** [comment]
v0.7.2 released and published to npmjs: 

- [github.com/uhppoted/uhppoted-nodejs](https://github.com/uhppoted/uhppoted-nodejs/releases/tag/v0.7.2)
- [npmjs.com/package.com/uhppoted](https://www.npmjs.com/package/uhppoted)

Let me know if you find anything catastrophically weird.

re. subscribe. There isn't one for npmjs, but you can subscribe to the github releases RSS feed:

- [uhppoted-nodejs/releases](https://github.com/uhppoted/uhppoted-nodejs/releases.atom)

**Comment by kBrausew** [comment]
thanks again, didn't find any fatal errors.
now there is a week break, then i will start with the ( real ) development...

One more question: needs "heartbeat"; back and forth across the listener; for the alive state. Do you have any idea?
So far I've been thinking of evaluating the "last" property of getEvents. The listener connection would not be involved in this case...

**Comment by twystd** [comment]
Oh great! Thanks for letting me know! I'll give it another couple of days and then close this issue out.

The "_heartbeat_" is an _ioBroker_ requirement? If it were me I would use `get-status` which returns the last event as well as other useful information and is also lighter weight than `get-events` (one UDP request as opposed to three for `get-events`) so is probably more reliable for a heartbeat.

re. _real development_. Good luck - hope it goes well :-)!

**Comment by uhppoted** [comment]
v0.7.2 released and published to npmjs: 

- [github.com/uhppoted/uhppoted-nodejs](https://github.com/uhppoted/uhppoted-nodejs/releases/tag/v0.7.2)
- [npmjs.com/package.com/uhppoted](https://www.npmjs.com/package/uhppoted)

Let me know if you find anything catastrophically weird.

re. subscribe. There isn't one for npmjs, but you can subscribe to the github releases RSS feed:

- [uhppoted-nodejs/releases](https://github.com/uhppoted/uhppoted-nodejs/releases.atom)
