### ISSUE TITLE
[Question] Remote connection

### ISSUE THREAD

**Issue by taufpate** [uhppoted/uhppoted-nodejs#6]
Hello, i want to know if there is a mode that i can connect to an remote controller (in totally different location) using port forwarding of remote router?

I've set a port forwarding  TCP/UDP from 60000 to 60001 ports and does not work,  but i dont know how to set broadcast in this case

**Comment by uhppoted** [comment]
Hi,

Yup, it's perfectly possible! If you're using the NodeJS library then you need to set up the remote controller IP _address:port_ in the `ctx` argument for the function call. 

There's a detailed example in [examples/common.js](https://github.com/uhppoted/uhppoted-nodejs/blob/master/examples/common.js), but basically the code looks like this:

```
const uhppoted = require('uhppoted')

const bind = '0.0.0.0'
const broadcast = '192.168.1.255:60000'
const listen = '0.0.0.0:60001'
const timeout = 5000
const debug = true

const controllers = [
  {
    deviceId: 405419896,
    address: '192.168.1.125:60000',
    forceBroadcast: false
  }]

const ctx = {
  config: new uhppoted.Config('example', bind, broadcast, listen, timeout, controllers, debug)
}

uhppoted.getDevice(ctx, 405419896)
  .then(response => {
    console.log('\nget-device:\n', response)
  })
  .catch(err => {
    console.log(`\n   *** ERROR ${err.message}\n`)
  })
```

If you Wireshark the communications for the above you'll see that a direct (i.e. non-broadcast) UDP message is being sent directly to 192.168.1.125:60000 - after that it's mostly getting the firewalls and NAT routing configured to allow and route the UDP messages correctly.

**Comment by taufpate** [comment]
Thks so much! works like a charm!

**Comment by uhppoted** [comment]
Oh great! That's good news :-) ... going to close this issue then. Feel free to reopen it if you need to...
