### ISSUE TITLE
[Question] Documentation

### ISSUE THREAD

**Issue by taufpate** [uhppoted/uhppoted-nodejs#8]
Hi! i have múltiple questions:

1.- How can I achieve that one door opens only in a specific time frame? (for one or all cards)

2.- in "addTask" method the "cards" key its the card index? what about if it's multiple cards or all cards?

**Comment by uhppoted** [comment]
Hi,

1. Time profiles allow you to set the days and periods during which a door can be opened. You can set combinations of specific days e.g. Monday, Wednesday, Friday and up to 3 segments per profile e.g. 08:00 to 11:30, 14:30 to 17:45, etc. And you can link multiple time profiles if you need more combinations. You then update the card records to use the time profile for the specific door. Ok, that's a bit unclear - let me give an example rather... 

   Assuming you want to enable door 4 only between 08:30 and 17:00 on weekdays for staff, you would first create a time    profile:
```
const deviceID = 405419896
const profile = {
  id: 29,
  valid: { from: '2022-01-01', to: '2022-12-31' },
  weekdays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  segments: [
    { start: '08:30', end: '17:00' }
  ]
}

uhppoted.setTimeProfile(ctx, deviceID, profile)
...
...
```

You would then assign the profile to door 4 for all the staff cards:

```
const validFrom = '2022-01-01'
const validUntil = '2022-12-31'
const doors = { 1: true, 2: false, 3: true, 4: 29 }

staff.forEach(card => {
   uhppoted.putCard(ctx, deviceID, card, validFrom, validUntil, doors)
   ...
   ...
}
```

2. The `cards` field in `AddTask` is for use with the `enable more cards` task and sets the number of people allowed access after the privileged 'more card' has swiped. AFAIK, it's primarily for things like escorting guests or guided tours - so e.g. if you were guiding a tour of 12 people your card would be assigned the _more cards_ privilege and `AddTask` + _enable more cards_ would be used to limit the number of people that could enter after you. I'm afraid that's about as much information as I have (it's not something I use). There are also a couple of additional functions on the TODO list around _more card_ and _first card_ privileges that would have to be implemented before it could really be used.

**Comment by taufpate** [comment]
once again thanks for your quick response and amazing work!, i'll try what you say and let you know
